server:
  port: 8888

spring:
  datasource:
    name: test
    url: jdbc:mysql:///zero?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1111
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #thymeleaf的配置是为了去掉html的校验
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
#配置日志
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    #      hibernate: ERROR
    #    配置打印sql(暂时没找到通配符方法)
    com.zero: debug
  file: log/log.log


#  resources:
#    static-locations: classpath:/public/ # 设置web访问html文件

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zero.user.entity,com.zero.user.vo # 注意：对应实体类的路径
#  config-location: classpath:mybatis/mybatis-config.xml  # mybatis配置文件